# Generated by Django 5.1.2 on 2024-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0003_venta_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.CharField(
                choices=[("Pagado", "Pagado"), ("Pendiente", "Pendiente")],
                default="Pagado",
                max_length=10,
            ),
        ),
    ]
